# env-type sets martini.Env, and should be "development", "test", or
# "production"
env-type: "development"

session-keys:
    # auth-key should be 16 or 32 characters
    auth-key: "dev-auth-key----"

    # encryption-key should be 16, 32, or 64 characters
    encryption-key: "dev-encryption-key--------------"

# Mongo connection details
mongo:
    host: "localhost:27017"
    db: "warren-dev"

# ElasticSearch connection details
elasticsearch:
    host: "localhost"
    port: 9200

smtp:
    host: "localhost"